//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesenvolvimentoWeb.Vendas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public int Id_Pedido { get; set; }
        public int Id_Produto { get; set; }
        public double Quantidade { get; set; }
    
        public virtual Pedido Pedidos_Info { get; set; }
        public virtual Produto Produto_Info { get; set; }
    }
}
