//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesenvolvimentoWeb.Vendas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendasEntities : DbContext
    {
        public VendasEntities()
            : base("name=VendasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<ITEM> ITENS { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOS { get; set; }
        public virtual DbSet<PRODUTO> PRODUTOS { get; set; }
    }
}
